# Generated by Django 5.1.1 on 2026-07-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_compensation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disruption_type', models.CharField(choices=[('cancellation', 'Cancellation'), ('delay', 'Delay'), ('denied_boarding', 'Denied Boarding')], max_length=32)),
                ('cancellation_notice', models.CharField(blank=True, choices=[('more_than_14_days', 'More than 14 days'), ('less_than_14_days', 'Less than 14 days'), ('on_flight_day', 'On flight day')], max_length=32, null=True)),
                ('delay_arrival', models.CharField(blank=True, choices=[('less_than_3h', 'Less than 3 hours'), ('more_than_3h', 'More than 3 hours'), ('connection_lost', 'Connection flight lost')], max_length=32, null=True)),
                ('voluntary_give_up', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=8, null=True)),
                ('denial_reason', models.CharField(blank=True, choices=[('overbooked', 'Flight overbooked'), ('aggressive_behavior', 'Aggressive behavior with staff'), ('intoxication', 'Intoxication'), ('unspecified', 'Unspecified reason')], max_length=32, null=True)),
                ('airline_mentioned_motive', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=16, null=True)),
                ('airline_motive', models.CharField(blank=True, choices=[('technical', 'Technical problem'), ('meteorological', 'Meteorological conditions'), ('strike', 'Strike'), ('airport_problems', 'Problems with airport'), ('crew_problems', 'Crew problems'), ('other', 'Other motives')], max_length=32, null=True)),
                ('incident_description', models.TextField(blank=True, default='')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disruption', to='cases.case')),
            ],
        ),
    ]
