# Generated by Django 5.1.1 on 2026-07-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_disruption'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='colleague',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
